import { useCallback, useEffect, useRef, useState } from "react";
import { useAudioIndex } from "@/lib/data/queries";
import { dataUrl } from "@/lib/data/source";

/**
 * Pronunciation playback.
 *
 * Three tiers, in order: a pre-generated clip from `data/audio/index.json`, the
 * browser's own text-to-speech when it has a voice for the locale, and silence.
 * The last tier is the important one - audio is generated by a separate
 * workflow that may not have run for a word yet, so a missing clip is an
 * expected state and never surfaces to the learner as an error.
 */

interface UseSpeakResult {
  speak: (text: string, locale: string) => void;
  isPlaying: boolean;
  isAvailable: (text: string, locale: string) => boolean;
}

/** Clip keys are exactly `${locale}:${text}` over the raw word text. */
const clipKey = (text: string, locale: string) => `${locale}:${text}`;

function getSpeechSynthesis(): SpeechSynthesis | null {
  if (typeof window === "undefined") return null;
  return "speechSynthesis" in window ? window.speechSynthesis : null;
}

/** "nl_NL" / "nl-nl" / "nl" all normalize toward comparability. */
const normalizeLocale = (locale: string) =>
  locale.toLowerCase().replace(/_/g, "-");

const primarySubtag = (locale: string) => normalizeLocale(locale).split("-")[0];

/** Exact locale match first, then any voice sharing the language subtag. */
function findVoice(
  voices: SpeechSynthesisVoice[],
  locale: string,
): SpeechSynthesisVoice | undefined {
  const wanted = normalizeLocale(locale);
  const language = primarySubtag(locale);
  return (
    voices.find((voice) => normalizeLocale(voice.lang) === wanted) ??
    voices.find((voice) => primarySubtag(voice.lang) === language)
  );
}

/**
 * The voice list is populated asynchronously in Chromium, so it is usually
 * empty on first read and arrives with a `voiceschanged` event.
 */
function useVoices(): SpeechSynthesisVoice[] {
  const [voices, setVoices] = useState<SpeechSynthesisVoice[]>([]);

  useEffect(() => {
    const synthesis = getSpeechSynthesis();
    if (!synthesis) return;

    const update = () => setVoices(synthesis.getVoices());
    update();
    synthesis.addEventListener("voiceschanged", update);
    return () => synthesis.removeEventListener("voiceschanged", update);
  }, []);

  return voices;
}

export function useSpeak(): UseSpeakResult {
  const { data: audioIndex } = useAudioIndex();
  const voices = useVoices();
  const [isPlaying, setIsPlaying] = useState(false);

  /**
   * One element for the whole app, created on first use. Constructing an
   * `Audio` per call leaks decoders and, on iOS, loses the user-gesture
   * unlock that lets playback start at all.
   */
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const getAudioElement = useCallback((): HTMLAudioElement => {
    let element = audioRef.current;
    if (!element) {
      element = new Audio();
      element.preload = "auto";
      element.addEventListener("ended", () => setIsPlaying(false));
      element.addEventListener("pause", () => setIsPlaying(false));
      element.addEventListener("error", () => setIsPlaying(false));
      audioRef.current = element;
    }
    return element;
  }, []);

  /** Stops whatever is currently making noise, from either tier. */
  const stop = useCallback(() => {
    const element = audioRef.current;
    if (element) {
      element.pause();
      element.currentTime = 0;
    }
    getSpeechSynthesis()?.cancel();
    setIsPlaying(false);
  }, []);

  const speakWithSynthesis = useCallback(
    (text: string, locale: string) => {
      const synthesis = getSpeechSynthesis();
      if (!synthesis) return;
      const voice = findVoice(voices, locale);
      if (!voice) return;

      const utterance = new SpeechSynthesisUtterance(text);
      utterance.voice = voice;
      utterance.lang = voice.lang;
      utterance.onstart = () => setIsPlaying(true);
      utterance.onend = () => setIsPlaying(false);
      utterance.onerror = () => setIsPlaying(false);
      synthesis.speak(utterance);
    },
    [voices],
  );

  const speak = useCallback(
    (text: string, locale: string) => {
      if (text === "") return;
      // A new request always wins over an in-flight one.
      stop();

      const clip = audioIndex?.clips[clipKey(text, locale)];
      if (!clip) {
        speakWithSynthesis(text, locale);
        return;
      }

      const element = getAudioElement();
      element.src = dataUrl(clip.path);
      setIsPlaying(true);
      element.play().catch(() => {
        // Indexed but unplayable (file pruned, codec unsupported, autoplay
        // blocked). Try TTS, then give up quietly.
        setIsPlaying(false);
        speakWithSynthesis(text, locale);
      });
    },
    [audioIndex, getAudioElement, speakWithSynthesis, stop],
  );

  const isAvailable = useCallback(
    (text: string, locale: string) => {
      if (text === "") return false;
      if (audioIndex?.clips[clipKey(text, locale)]) return true;
      return findVoice(voices, locale) !== undefined;
    },
    [audioIndex, voices],
  );

  useEffect(() => {
    return () => {
      const element = audioRef.current;
      if (element) {
        element.pause();
        element.removeAttribute("src");
        element.load();
        audioRef.current = null;
      }
      getSpeechSynthesis()?.cancel();
    };
  }, []);

  return { speak, isPlaying, isAvailable };
}
